/**
 * Application route map — single source of truth for navigation & redirects.
 */
export const routes = {
  marketing: {
    home: "/",
    about: "/about",
    meetFouza: "/meet-fouza",
    team: "/meet-fouza",
    services: "/services",
    service: (slug: string) => `/services/${slug}` as const,
    conditions: "/conditions",
    condition: (slug: string) => `/conditions/${slug}` as const,
    pricing: "/pricing",
    faq: "/faq",
    contact: "/contact",
    blog: "/blog",
    blogPost: (slug: string) => `/blog/${slug}` as const,
    reviews: "/reviews",
    privacy: "/privacy",
    terms: "/terms",
  },
  booking: {
    root: "/book",
    confirm: "/book/confirm",
    success: "/book/success",
  },
  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    callback: "/auth/callback",
    logout: "/auth/logout",
  },
  portal: {
    root: "/portal",
    appointments: "/portal/appointments",
    programmes: "/portal/programmes",
    invoices: "/portal/invoices",
    forms: "/portal/forms",
    documents: "/portal/documents",
    notifications: "/portal/notifications",
    profile: "/portal/profile",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin",
    patients: "/admin/patients",
    patient: (id: string) => `/admin/patients/${id}` as const,
    appointments: "/admin/appointments",
    clinicalNotes: "/admin/clinical-notes",
    programmes: "/admin/programmes",
    consentForms: "/admin/consent-forms",
    billing: "/admin/billing",
    invoices: "/admin/billing/invoices",
    statements: "/admin/billing/statements",
    reviews: "/admin/reviews",
    blog: "/admin/blog",
    practice: "/admin/practice",
    settings: "/admin/settings",
    users: "/admin/users",
    availability: "/admin/availability",
    documents: "/admin/documents",
  },
  api: {
    health: "/api/health",
  },
} as const;
